# Generated by Django 3.0.8 on 2020-07-02 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('note', models.TextField()),
                ('is_task', models.NullBooleanField(default=False)),
                ('attachment', models.FileField(upload_to='uploads/')),
                ('note_type', models.CharField(choices=[('NEW', 'New'), ('RDY', 'Ready'), ('WIP', 'In Progress'), ('TEST', 'Ready for test'), ('DONE', 'Done')], default='NEW', max_length=4)),
                ('tag', models.ManyToManyField(to='api.Tag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.User')),
            ],
        ),
    ]
